---
# This creates the workspace directory in the users home
workspace: ".myosx"

# dotfile management
dotfiles:
  manage: true
  repo: 'https://github.com/surminus/dotfiles.git'
  files:
  - ackrc
  - gitconfig
  - vimrc
  - zshrc
