---
# This creates the named workspace directory in the users home
workspace: '.myosx'

# Manage your dotfiles
dotfiles:
  manage: true
  repo: 'https://github.com/surminus/dotfiles.git'
  files:
  - ackrc
  - gitconfig
  - vimrc
  - zshrc

# Manage homebrew packages
homebrew:
  packages:
    brew:
      - 'ack'
      - 'gcc'
      - 'git'
      - 'go'
      - 'hub'
      - 'imagemagick'
      - 'pass'
      - 'rbenv'
      - 'rbenv-aliases'
      - 'rbenv-bundler'
      - 'vim'
      - 'wget'
      - 'zsh'
    tap:
      - 'caskroom/cask'
